import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { genRound } from '@/lib/genRounds'
import Card from '@/components/card/card'
import { useCallback, useEffect, useState } from 'react'
import { findSolution } from '@/lib/findSolution'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [cardsVal, setCardsVal] = useState([0,0,0,0]);
  const [refreshCount, setRefreshCount] = useState(0);
  const [solution, setSolution] = useState<string[]>([]);
  const [showAnswer, setShowAnswer] = useState(false);

  const nextRound = () => {
    setRefreshCount(refreshCount + 1);
  }

  const updateCards = () => {
    const round = genRound();
    setCardsVal(round);
  }

  const findPossibleSolutions = () => {
    const _solution = findSolution(cardsVal);
    if (_solution != undefined) {
      setSolution(_solution);
    } else {
      setSolution([]);
    }
  };

  const clickShowAnswer = () => {
    setShowAnswer(true);
  }
  
  useEffect(() => {
    setShowAnswer(false)
    updateCards();
  }, [refreshCount])

  useEffect(() => {
    findPossibleSolutions()
  }, [cardsVal])
  
  return (
    <>
      <Head>
        <title>Super 24</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{ display: 'flex' }}>
          {cardsVal.map((c, id) => <Card key={`card-${id}`} value={c} />)}
        </div>
        <div>
          <div style={{ height: 70, textAlign: 'center' }}>
            {showAnswer && <div>{solution.length > 0 ? solution.join(' ') : 'i give up'}</div>}
          </div>
          <button 
            style={{
              padding: 12,
              fontSize: 30,
            }}  
            onClick={clickShowAnswer}
          >
            show answer
          </button>
        </div>
        <div>
          <button
            style={{
              padding: 12,
              fontSize: 30,
            }} 
            onClick={nextRound}
          >
            next round
          </button>
        </div>
      </main>
    </>
  )
}
