import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useRound } from '@/hooks/useRound'
import Card from '@/components/card/card'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [cardsVal, setCardsVal] = useState([0,0,0,0]);
  const [refreshCount, setRefreshCount] = useState(0);

  const nextRound = () => {
    setRefreshCount(refreshCount + 1);
  }

  const updateCards = () => {
    const round = useRound();
    setCardsVal(round);

  }
  
  useEffect(() => {
    updateCards();
  }, [refreshCount, updateCards])
  
  return (
    <>
      <Head>
        <title>Super 24</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{ display: 'flex' }}>
          {cardsVal.map((c, id) => <Card key={`card-${id}`} value={c} />)}
        </div>
        <div>
          <button
            style={{
              padding: 12,
              fontSize: 30,
            }} 
            onClick={nextRound}
          >
            next round
          </button>
        </div>
      </main>
    </>
  )
}
